# Datasets used  

## To follow along  

All the data in this handbook can be downloaded from the **["data" folder](https://github.com/nsbatra/Epi_R_handbook/tree/master/data)** of our Github repository.  

To "follow along" with any of the handbook examples that use the `linelist` dataset, download and load either the "linelist_raw.xlsx" (for the Cleaning page), or "linelist_cleaned.rds" (for any other page).  

## Background information  

Below are more details about some of the data: 

* The case linelist  
     * A *simulated* Ebola outbreak, expanded by the handbook team from the `ebola_sim` practice dataset in the **outbreaks** package  
     
* Aggregated counts  
     * A simulated dataset of malaria counts by age, day, and facility in a fictional region, which can be downloaded from the data folder noted above as "district_count_data.xlsx"  
     
* Time series and outbreak detection  
     * Campylobacter cases reported in Germany 2002-2011. Available from **surveillance** package
     * Climate data (temperature in degrees celsius and rain fail in millimetres) in Germany 2002-2011. Downloaded from the EU Copernicus satellite reanalysis dataset using the **ecmwfr** package as explained in the time series page.  

* GIS page shapefiles  
     * Downloaded from the Humanitarian Data Exchange (HDX) - see links in the GIS basics page  

* Phylogenetic tree data  
     * Newick file of phylogenetic tree constructed from whole genome sequencing of 299 Shigella sonnei samples and corresponding sample data.
     * The Belgian samples and resulting data are kindly provided by the Belgian NRC for Salmonella and Shigella in the scope of a project conducted by an ECDC EUPHEM Fellow, and will also be published in a manuscript.  
     * The international data are openly available on public databases (ncbi) and have been previously published.  
     


