
# ggplot tips { }  

UNDER CONSTRUCTION  

https://www.tidyverse.org/blog/2018/07/ggplot2-3-0-0/

graph gallery

<!-- ======================================================= -->
## Overview {  }




<!-- ======================================================= -->
## Preparation {  }




<!-- ======================================================= -->
## Intro to `ggplot()`





<!-- ======================================================= -->
## Common geoms  



<!-- ======================================================= -->
## Facets/small-multiples  

http://www.cookbook-r.com/Graphs/Facets_(ggplot2)/#modifying-facet-label-text
labellers
https://ggplot2.tidyverse.org/reference/labellers.html
facet_wrap vs. facet_grid
Using option `label_wrap_gen` in facet_wrap to have multiple strip lines
labels and colors of strips


<!-- ======================================================= -->
## Ordering  

fct_reorder, na.rm=T median
fct_infreq
https://forcats.tidyverse.org/reference/fct_reorder.html
https://forcats.tidyverse.org/reference/fct_inorder.html
https://cmdlinetips.com/2019/02/how-to-reorder-a-boxplot-in-r/
https://rstudio-pubs-static.s3.amazonaws.com/268470_afbfbdcbc6394f89a00a689b866684b4.html

gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarize(md = median(pop)) %>%
  mutate(continent = fct_reorder(continent, md)) %>%
  ggplot(aes(continent, md)) +
  geom_col()
 
https://www.r-graph-gallery.com/267-reorder-a-variable-in-ggplot2.html
Legend order
https://stackoverflow.com/questions/38425908/reverse-stacking-order-without-affecting-legend-order-in-ggplot2-bar-charts





<!-- ======================================================= -->
## Titles and Labels  

ggtitle
labs()
Axis text vertical adjustment
rotation
Labellers


<!-- ======================================================= -->
## Background

limit range with limit() and coord_cartesian(), ylim(), or scale_x_continuous()
theme_classic()


<!-- ======================================================= -->
## Axes
scale_x_
scale_y_
expand = c(0,0)
coord_flip()
tick marks
See epicurves page for dealing with date breaks etc.





<!-- ======================================================= -->
## Theme  

Caption alignment
https://stackoverflow.com/questions/64701500/left-align-ggplot-caption



<!-- ======================================================= -->
## Legends  

remove
remove title
using fill = or color = in labs()
flip order / don't flip order
move location
color?    theme(legend.title = element_text(colour="chocolate", size=16, face="bold"))+ scale_color_discrete(name="This color is\ncalled chocolate!?")
Color of boxes behind points in legend 
     theme(legend.key=element_rect(fill='pink'))   or use fill = NA to remove them. http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/ 
Change size of symbols in legend only guides(colour = guide_legend(override.aes = list(size=4)))


Turn off a layer in the legend
geom_text(data=nmmaps, aes(date, temp, label=round(temp)), size=4)
geom_text(data=nmmaps, aes(date, temp, label=round(temp), size=4), show_guide=FALSE)

Force a legend even if there is no aes(). 
ggplot(nmmaps, aes(x=date, y=o3))+
     geom_line(aes(color="Important line"))+
     geom_point(aes(color="My points"))
Control the shape in the legend with guides - a list with linetype and shape
ggplot(nmmaps, aes(x=date, y=o3))+geom_line(aes(color="Important line"))+
   geom_point(aes(color="Point values"))+
  scale_colour_manual(name='', values=c('Important line'='grey', 'Point values'='red'), guide='legend') +
  guides(colour = guide_legend(override.aes = list(linetype=c(1,0)
                                                      , shape=c(NA, 16))))
http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/
<!-- ======================================================= -->
## Colors {  }






<!-- ======================================================= -->
## Smart Labeling {  }
ggrepel



<!-- ======================================================= -->
## Highlighting {  }

highlighting one line among many etc
gghighlight




<!-- ======================================================= -->
## Time axes {  }




<!-- ======================================================= -->
## Dual axes {  }

### Cowplot {-}


<!-- ======================================================= -->
## Adding shapes {  }



<!-- ======================================================= -->
## Animations {  }

## Resources 

ggplot cheatsheet
https://r4ds.had.co.nz/factors.html

http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/
