# Suggested packages

Below is a long list of suggested packages for common epidemiological work in R. You can copy this code, run it, and all of these packages will install from CRAN and load for use in the current R session. If a package is already installed, it will be loaded for use only.  

You can modify the code with `#` symbols to exclude any packages you do not want.  

Of note:  

* Install the **pacman** package first before running the below code. You can do this with `install.packages("pacman")`. In this handbook we emphasize `p_load()` from **pacman**, which installs the package if necessary *and* loads it for use in the current R session. You can also load packages that are already installed with `library()` from **base** R.  
* In the code below, packages that are included when installing/loading another package are indicated by an indent and hash. For example how **ggplot2** is listed under **tidyverse**.  
* The code below only installs packages available on CRAN - not from Github  
* If multiple packages have functions with the same name, *masking* can occur when the function from the more recently-loaded package takes precedent. Read more in the [R basics] page. Consider using the package **conflicted** to manage such conflicts.  
* See the [R basics] section on packages for more information on **pacman** and masking.  

To see the versions of R, RStudio, and R packages used during the production of this handbook, see the page on [Editorial and technical notes].  


```{r, eval=F}

# List of useful epidemiology R packages  

pacman::p_load(
     
     # learning R
     learnr,   # interactive tutorials in RStudio
        
     # project and file management
     here,     # filepaths relative to root project folder
     rio,      # import/export of many types of data
     openxlsx, # import/export of Excel workbooks 
     
     # package install and management
     pacman,   # package install/load
     renv,     # managing versions of packages when working in collaborative groups
     remotes,  # install from github
     
     # General data management
     tidyverse,    # includes many packages for tidy data wrangling and presentation
          #dplyr,
          #tidyr,
          #ggplot2,
     linelist,     # cleaning linelists
     lubridate,    # working with dates
     naniar,       # assessing missing data
     
     # statistics  
     gtsummary,    # making descriptive and statistical tables
     janitor,      # tables and data cleaning
     
     # epidemic modeling
     epicontacts,  # Analysing transmission networks
     EpiNow2,      # Rt estimation
     EpiEstim,     # Rt estimation
     projections,  # Incidence projections
     incidence2,   # Make epicurves and handle incidence data
     i2extras,     #
     epitrix,      # Useful epi functions
     distcrete,    # Discrete delay distributions
     
     
     # plots - general
     #ggplot2,         # included in tidyverse
     cowplot,          # combining plots
     RColorBrewer,     # color scales
     
     # plots - specific types
     DiagrammeR,       # diagrams using DOT language
     incidence,        # epidemic curves
     gghighlight,      # highlight a subset
     ggrepel,          # smart labels
     
     # gis
     sf,               # to manage spatial data using a Simple Feature format
     tmap,             # to produce simple maps, works for both interactive and static maps
     OpenStreetMap,    # to add OSM basemap in ggplot map
     
     # routine reports  
     rmarkdown,        # produce PDFs, Word Documents, Powerpoints, and HTML files
     reportfactory,    # Auto-organization of Rmarkdown outputs
     
     # tables
     knitr,            # report generation, kable() for html tables
     flextable,        # HTML tables
     #DT,              # HTML tables (alternative)
     #gt,              # HTML tables (alternative)
     #huxtable,        # a HTML tables (alternative) 
     
     # phylogenetics  
     ggtree,           # visualization and annotation of trees
     ape,              # analysis of phylogenetics and evolution
     
     # interactive
     plotly,           # interactive graphics
     shiny             # interactive web apps  
)


```

