
# Plotting discrete variables  {.tabset .tabset-fade}  



<!-- ======================================================= -->
## Overview {.tabset .tabset-fade .tabset-pills}

Keep the title of this section as "Overview".  
This tab should include:  

* Textual overview of the purpose of this page  
* Small image showing outputs   



<!-- ======================================================= -->
## Preparation {.tabset .tabset-fade .tabset-pills}

Keep the title of this section as "Preparation".  
Data preparation steps such as:  

* Loading dataset  
* Adding or changing variables  
* melting, pivoting, grouping, etc.   

<!-- ======================================================= -->
## base R {.tabset .tabset-fade .tabset-pills}




<!-- ======================================================= -->
## `ggplot2` {.tabset .tabset-fade .tabset-pills}

This tab can be re-named. 
This tab should demonstrate execution of the task a more standard/core package (e.g. ggplot2, or base R) that allows for more flexibility in the output or more package stability. For example, showing how to create an epicurve using *ggplot2*. 


<!-- ======================================================= -->
### Option 2 sub-tab {.tabset .tabset-fade .tabset-pills}

Sub-tabs if necessary. Re-name as needed.



<!-- ======================================================= -->
## Resources {.tabset .tabset-fade .tabset-pills}

This tab should stay with the name "Resources".
Links to other online tutorials or resources.





