
# Survey analysis {.tabset .tabset-fade}  

UNDER CONSTRUCTION

<!-- ======================================================= -->
## Overview {.tabset .tabset-fade .tabset-pills}

Keep the title of this section as "Overview".  
This tab should include:  

* Textual overview of the purpose of this page  
* Small image showing outputs   



<!-- ======================================================= -->
## Preparation {.tabset .tabset-fade .tabset-pills}

Keep the title of this section as "Preparation".  
Data preparation steps such as:  

* Loading dataset  
* Adding or changing variables  
* melting, pivoting, grouping, etc.   

<!-- ======================================================= -->
### sub-tab 1 {.tabset .tabset-fade .tabset-pills}

Can be used to separate major steps of data preparation. Re-name as needed


<!-- ======================================================= -->
### sub-tab 2 {.tabset .tabset-fade .tabset-pills}

Can be used to separate major steps of data preparation. Re-name as needed.



<!-- ======================================================= -->
## From data frame {.tabset .tabset-fade .tabset-pills}

<!-- ======================================================= -->
## Overview {.tabset .tabset-fade .tabset-pills}

<!-- ======================================================= -->
## Weighting {.tabset .tabset-fade .tabset-pills}

<!-- ======================================================= -->
## Random selection {.tabset .tabset-fade .tabset-pills}

<!-- ======================================================= -->
## Resources {.tabset .tabset-fade .tabset-pills}

This tab should stay with the name "Resources".
Links to other online tutorials or resources.




