
# Time series analysis {.tabset .tabset-fade}  

<!-- ======================================================= -->
## Overview {.tabset .tabset-fade .tabset-pills}

This tab demonstrates the use of several packages for time series analysis. 
It primarily relies on packages from the [**tidyverts**](https://tidyverts.org/) 
family, but will also use the RECON [**trending**](https://github.com/reconhub/trending) 
package to fit models that are more appropriate for infectious disease epidemiology. 

1.  Time series data 
2.  Descriptive analysis 
3.  Fitting regressions
4.  Relation of two time series 
5.  Interrupted time series
6.  Outbreak detection


<!-- ======================================================= -->
## Preparation {.tabset .tabset-fade .tabset-pills}

Keep the title of this section as "Preparation".  
Data preparation steps such as:  

* Loading dataset  
* Adding or changing variables  
* melting, pivoting, grouping, etc.   

<!-- ======================================================= -->
### sub-tab 1 {.tabset .tabset-fade .tabset-pills}

Can be used to separate major steps of data preparation. Re-name as needed


<!-- ======================================================= -->
### sub-tab 2 {.tabset .tabset-fade .tabset-pills}

Can be used to separate major steps of data preparation. Re-name as needed.



<!-- ======================================================= -->
## Option 1 {.tabset .tabset-fade .tabset-pills}

This tab can be renamed. 
This tab should demonstrate execution of the task using recommended package/approach. For example, using a package customized for this task where the execution is simple and fast but perhaps less customizable. For example using *incidence* package to create an epicurve.


<!-- ======================================================= -->
### Option 1 sub-tab {.tabset .tabset-fade .tabset-pills}

Sub-tabs if necessary. Re-name as needed.



<!-- ======================================================= -->
## Option 2 {.tabset .tabset-fade .tabset-pills}

This tab can be re-named. 
This tab should demonstrate execution of the task a more standard/core package (e.g. ggplot2, or base R) that allows for more flexibility in the output or more package stability. For example, showing how to create an epicurve using *ggplot2*. 


<!-- ======================================================= -->
### Option 2 sub-tab {.tabset .tabset-fade .tabset-pills}

Sub-tabs if necessary. Re-name as needed.



<!-- ======================================================= -->
## Resources {.tabset .tabset-fade .tabset-pills}

This tab should stay with the name "Resources".
Links to other online tutorials or resources.





