**This is one page of the R Handbook for Epidemiologists, but is being printed as a stand-alone page.**  

**You can find the complete handbook on [Github](https://github.com/nsbatra/Epi_R_handbook)**  


```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      collapse = TRUE,
                      fig.width = 8,
                      fig.height = 6,
                      dpi = 150,
                      warning = FALSE,
                      message = FALSE)
```

```{css, echo = FALSE}
# Sets color of header levels
h1, #TOC>ul>li {
  color: #A93226;          d
  font-family:  "Times";
  font-weight: bold;
}

h2, #TOC>ul>ul>li {
  color: #229954;          
  font-family:  "Times";
  font-weight: bold;
}

h3, #TOC>ul>ul>ul>li {
  color: #3498DB;          
  font-family:  "Times";
  font-weight: bold;
}

```


```{r echo=FALSE, include=TRUE}
#Enables "copy to clipboard" icons   https://rlesur.github.io/klippy/articles/klippy.html
#install.packages("remotes")
#remotes::install_github("rlesur/klippy")

klippy::klippy(position = c('top', 'right'))
```


```{r}
source(here::here("load_core_packages.R"))
```


```{r}
# import the raw ebola linelist
linelist_raw <- rio::import(here::here("data", "ebola_simulated.xlsx"))

# import the cleaned ebola linelist
linelist <- rio::import(here::here("data", "linelist_cleaned.rds"))

# import the counts data - district level
#count_data <- rio::import(here::here("data", "district_count_data.xlsx"))

# import the count data - facility level
count_data <- rio::import(here::here("data", "facility_count_data.csv"))

# import the population demographics data
#pop <- rio::import(here::here("data", "country_demographics.csv"))

# import the likert- survey responses data
#likert_data <- rio::import(here::here("data", "likert_data.csv"))

```




