<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>17 Standardization | R Handbook for Epidemiologists</title>
<meta name="author" content="the handbook team">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.2"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.6/header-attrs.js"></script><script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.5.3/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.5.3/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.3.9000/tabs.js"></script><script src="libs/bs3compat-0.2.3.9000/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script><link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="libs/datatables-binding-0.15/datatables.js"></script><link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script><link href="libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet">
<script src="libs/nouislider-7.0.10/jquery.nouislider.min.js"></script><link href="libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet">
<script src="libs/selectize-0.12.0/selectize.min.js"></script><link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet">
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script><link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet">
<script src="libs/leaflet-1.3.1/leaflet.js"></script><link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet">
<script src="libs/proj4-2.6.2/proj4.min.js"></script><script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script><link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet">
<script src="libs/leaflet-binding-2.0.4.1/leaflet.js"></script><script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script><script src="libs/leaflet-providers-plugin-2.0.4.1/leaflet-providers-plugin.js"></script><link href="libs/tabwid-1.0.0/tabwid.css" rel="stylesheet">
<script src="libs/viz-1.8.2/viz.js"></script><link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
<script src="libs/grViz-binding-1.0.6.1/grViz.js"></script><script src="libs/d3-4.5.0/d3.min.js"></script><script src="libs/sankey-1/sankey.js"></script><script src="libs/sankeyNetwork-binding-0.4/sankeyNetwork.js"></script><script src="libs/plotly-binding-4.9.3/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script><link href="libs/vis-4.20.1/vis.css" rel="stylesheet">
<script src="libs/vis-4.20.1/vis.min.js"></script><script src="libs/visNetwork-binding-2.0.9/visNetwork.js"></script><link href="libs/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet">
<script src="libs/plotly-basic-1.57.1/plotly-basic-1.57.1.min.js"></script><script src="libs/plotly-cartesian-1.57.1/plotly-cartesian-1.57.1.min.js"></script><script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/mark.js@8.11.1/dist/mark.min.js"></script><!-- CSS --><link rel="stylesheet" href="style_bs4.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">R Handbook for Epidemiologists</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Welcome - THIS IS A DRAFT</a></li>
<li class="book-part">About this book</li>
<li><a class="" href="style-and-editorial-notes.html"><span class="header-section-number">1</span> Style and editorial notes</a></li>
<li><a class="" href="datasets-used.html"><span class="header-section-number">2</span> Datasets used</a></li>
<li class="book-part">Basics</li>
<li><a class="" href="r-basics.html"><span class="header-section-number">3</span> R Basics</a></li>
<li><a class="" href="importing-and-exporting.html"><span class="header-section-number">4</span> Importing and exporting</a></li>
<li><a class="" href="r-projects.html"><span class="header-section-number">5</span> R projects</a></li>
<li><a class="" href="suggested-packages.html"><span class="header-section-number">6</span> Suggested packages</a></li>
<li class="book-part">Data Management</li>
<li><a class="" href="cleaning-data.html"><span class="header-section-number">7</span> Cleaning data</a></li>
<li><a class="" href="working-with-dates.html"><span class="header-section-number">8</span> Working with dates</a></li>
<li><a class="" href="missing-data.html"><span class="header-section-number">9</span> Missing data</a></li>
<li><a class="" href="grouping-data.html"><span class="header-section-number">10</span> Grouping data</a></li>
<li><a class="" href="joining-data.html"><span class="header-section-number">11</span> Joining data</a></li>
<li><a class="" href="characters-and-strings.html"><span class="header-section-number">12</span> Characters and strings</a></li>
<li><a class="" href="de-duplication.html"><span class="header-section-number">13</span> De-duplication</a></li>
<li><a class="" href="iteration-and-loops.html"><span class="header-section-number">14</span> Iteration and loops</a></li>
<li class="book-part">Analysis</li>
<li><a class="" href="descriptive-analysis.html"><span class="header-section-number">15</span> Descriptive analysis</a></li>
<li><a class="" href="simple-statistical-tests.html"><span class="header-section-number">16</span> Simple statistical tests</a></li>
<li><a class="active" href="standardization.html"><span class="header-section-number">17</span> Standardization</a></li>
<li><a class="" href="moving-averages.html"><span class="header-section-number">18</span> Moving averages</a></li>
<li><a class="" href="outbreak-detection.html"><span class="header-section-number">19</span> Outbreak detection</a></li>
<li><a class="" href="time-series-analysis.html"><span class="header-section-number">20</span> Time series analysis</a></li>
<li><a class="" href="epidemic-modeling.html"><span class="header-section-number">21</span> Epidemic modeling</a></li>
<li><a class="" href="modeling.html"><span class="header-section-number">22</span> Modeling</a></li>
<li><a class="" href="survey-analysis.html"><span class="header-section-number">23</span> Survey analysis</a></li>
<li><a class="" href="survival-analysis-1.html"><span class="header-section-number">24</span> Survival analysis</a></li>
<li><a class="" href="gis-basics.html"><span class="header-section-number">25</span> GIS basics</a></li>
<li class="book-part">Data Vizualization</li>
<li><a class="" href="ggplot-tips.html"><span class="header-section-number">26</span> ggplot tips</a></li>
<li><a class="" href="epidemic-curves.html"><span class="header-section-number">27</span> Epidemic curves</a></li>
<li><a class="" href="plot-continuous-data.html"><span class="header-section-number">28</span> Plot continuous data</a></li>
<li><a class="" href="plot-categorical-data.html"><span class="header-section-number">29</span> Plot categorical data</a></li>
<li><a class="" href="tables.html"><span class="header-section-number">30</span> Tables</a></li>
<li><a class="" href="age-pyramids.html"><span class="header-section-number">31</span> Age pyramids</a></li>
<li><a class="" href="diagrams.html"><span class="header-section-number">32</span> Diagrams</a></li>
<li><a class="" href="combination-analysis.html"><span class="header-section-number">33</span> Combination analysis</a></li>
<li><a class="" href="heatmaps-density-plots.html"><span class="header-section-number">34</span> Heatmaps &amp; density plots</a></li>
<li><a class="" href="transmission-chains.html"><span class="header-section-number">35</span> Transmission chains</a></li>
<li><a class="" href="phylogenetic-trees.html"><span class="header-section-number">36</span> Phylogenetic trees</a></li>
<li><a class="" href="interactive-plots.html"><span class="header-section-number">37</span> Interactive plots</a></li>
<li class="book-part">Advanced</li>
<li><a class="" href="errors-warnings-1.html"><span class="header-section-number">38</span> Errors &amp; warnings</a></li>
<li><a class="" href="advanced-rstudio.html"><span class="header-section-number">39</span> Advanced RStudio</a></li>
<li><a class="" href="relational-databases.html"><span class="header-section-number">40</span> Relational databases</a></li>
<li><a class="" href="routine-reports.html"><span class="header-section-number">41</span> Routine reports</a></li>
<li><a class="" href="r-markdown-1.html"><span class="header-section-number">42</span> R Markdown</a></li>
<li><a class="" href="shiny-and-dashboards.html"><span class="header-section-number">43</span> Shiny and dashboards</a></li>
<li><a class="" href="collaboration.html"><span class="header-section-number">44</span> Collaboration</a></li>
<li><a class="" href="writing-functions.html"><span class="header-section-number">45</span> Writing functions</a></li>
<li><a class="" href="r-on-network-drives.html"><span class="header-section-number">46</span> R on network drives</a></li>
<li><a class="" href="directory-interactions.html"><span class="header-section-number">47</span> Directory interactions</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="standardization" class="section level1" number="17">
<h1>
<span class="header-section-number">17</span> Standardization<a class="anchor" aria-label="anchor" href="#standardization"><i class="fas fa-link"></i></a>
</h1>
<p>This page will show you two ways to standardize an outcome, such as hospitalizations or mortality, by characteristics such as age and sex.</p>
<ul>
<li>Using <strong>dsr</strong> package</li>
<li>Using <strong>PHEindicatormethods</strong> package
<code>{#title_tag  }</code>
</li>
</ul>
<!-- ======================================================= --><div id="overview-10" class="section level2" number="17.1">
<h2>
<span class="header-section-number">17.1</span> Overview<a class="anchor" aria-label="anchor" href="#overview-10"><i class="fas fa-link"></i></a>
</h2>
<p>There are two main ways to standardize: direct and indirect standardization.
Let’s say we would like to standardize mortality by age and sex for country A and country B, and compare the standardized rates between these countries.</p>
<ul>
<li>For direct standardization, you will have to know the number of the at-risk population and the number of deaths for each stratum of age and sex, for country A and country B. One stratum in our example could be females between ages 15-44.</li>
<li>For indirect standardization, you only need to know the total number of deaths and the age- and sex structure of each country. This option is therefore feasible if age- and sex-specific mortality rates or population numbers are not available. Indirect standardization is furthermore preferable in case of small numbers per stratum, as estimates in direct standardization would be influenced by substantial sampling variation.</li>
</ul>
<!-- ======================================================= -->
</div>
<div id="preparation-8" class="section level2" number="17.2">
<h2>
<span class="header-section-number">17.2</span> Preparation<a class="anchor" aria-label="anchor" href="#preparation-8"><i class="fas fa-link"></i></a>
</h2>
<h2>
Preparation
<a class="anchor" aria-label="anchor" href="#preparation-8"><i class="fas fa-link"></i></a>
</h2>
<p>To show how standardization is done, we will use the <code>country_demographics</code> (country A) and <code>country_demographics_2</code> (country B) datasets, by age (in 5 year categories) and sex (female, male). We will add our own fictitious mortality data to these datasets. To make the dataset ready for use, we will perform the following steps:</p>
<ol style="list-style-type: decimal">
<li>Load packages</li>
<li>Load datasets</li>
<li>Create one row per stratum of age and sex</li>
<li>Add number of deaths per stratum</li>
<li>Prepare reference population (standard population)</li>
</ol>
<p>Alternatively, instead of just adding mortality numbers per stratum, you may have a dataset per country (or per group within a country, province, city, or other catchment area) with one row for each death and information on age and sex for each (or a significant proportion) of these deaths. In this case, you can aggregate by age and sex to create a dataset with numbers per stratum, and then add this to the dataset with population numbers per stratum.</p>
<p>We also need a reference population, the standard population. There are several standard populations available, for the purpose of this exercise we will use the <code>world_standard_population_by_sex</code>. The World standard population is based on the populations of 46 countries and was developed in 1960. I found the website of the NHS Schotland quite informative on the European Standard Population, World Standard Population and Scotland Standard Population: <a href="https://www.opendata.nhs.scot/dataset/standard-populations" class="uri">https://www.opendata.nhs.scot/dataset/standard-populations</a></p>
<!-- ======================================================= -->
<div id="load-packages-1" class="section level3" number="17.2.1">
<h3>
<span class="header-section-number">17.2.1</span> Load packages<a class="anchor" aria-label="anchor" href="#load-packages-1"><i class="fas fa-link"></i></a>
</h3>
<p><span style="color: orange;"><strong><em>CAUTION:</em></strong> If you have a newer version of R, the <strong>dsr</strong> package cannot be directly downloaded as it is archived. However, it is still available from the CRAN archive. You can install and use this one. </span></p>
<p>For non-Mac users:</p>
<div class="sourceCode" id="cb727"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span><span class="op">(</span><span class="va">Rtools</span><span class="op">)</span>
<span class="va">packageurl</span> <span class="op">&lt;-</span> <span class="st">"https://cran.r-project.org/src/contrib/Archive/dsr/dsr_0.2.2.tar.gz"</span>
<span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="va">packageurl</span>, repos<span class="op">=</span><span class="cn">NULL</span>, type<span class="op">=</span><span class="st">"source"</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb728"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Other solution that may work</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span><span class="op">(</span><span class="va"><a href="https://devtools.r-lib.org/">devtools</a></span><span class="op">)</span>
<span class="fu">devtools</span><span class="fu">::</span><span class="fu"><a href="https://devtools.r-lib.org//reference/remote-reexports.html">install_version</a></span><span class="op">(</span><span class="st">"dsr"</span>, version<span class="op">=</span><span class="st">"0.2.2"</span>, repos<span class="op">=</span><span class="st">"http:/cran.us.r.project.org"</span><span class="op">)</span></code></pre></div>
<p>For Mac users:</p>
<div class="sourceCode" id="cb729"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span><span class="op">(</span><span class="va"><a href="https://devtools.r-lib.org/">devtools</a></span><span class="op">)</span>
<span class="fu">devtools</span><span class="fu">::</span><span class="fu"><a href="https://devtools.r-lib.org//reference/remote-reexports.html">install_version</a></span><span class="op">(</span><span class="st">"dsr"</span>, version<span class="op">=</span><span class="st">"0.2.2"</span>, repos<span class="op">=</span><span class="st">"https://mac.R-project.org"</span><span class="op">)</span></code></pre></div>
<p>Load the packages required for this analysis:</p>
<div class="sourceCode" id="cb730"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">rio</span>,       <span class="co"># to import data</span>
               <span class="va">here</span>,      <span class="co"># to locate files</span>
               <span class="va">tidyverse</span>, <span class="co"># to clean, handle, and plot the data (includes ggplot2 package)</span>
               <span class="va">frailtypack</span>, <span class="co"># needed for dsr, for frailty models</span>
               <span class="va">dsr</span>,  
               <span class="va">PHEindicatormethods</span><span class="op">)</span></code></pre></div>
<!-- ======================================================= -->
</div>
<div id="load-data-2" class="section level3" number="17.2.2">
<h3>
<span class="header-section-number">17.2.2</span> Load data<a class="anchor" aria-label="anchor" href="#load-data-2"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb731"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Country A</span>
<span class="va">countryA_demo_data</span> <span class="op">&lt;-</span> <span class="fu">rio</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/rio/man/import.html">import</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"country_demographics.csv"</span><span class="op">)</span><span class="op">)</span>
<span class="va">countryA_demo_data</span><span class="op">$</span><span class="va">Country</span> <span class="op">&lt;-</span> <span class="st">"A"</span> <span class="co"># add column name with the name of the country</span>

<span class="co"># Country B</span>
<span class="va">countryB_demo_data</span> <span class="op">&lt;-</span> <span class="fu">rio</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/rio/man/import.html">import</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"country_demographics_2.csv"</span><span class="op">)</span><span class="op">)</span>
<span class="va">countryB_demo_data</span><span class="op">$</span><span class="va">Country</span> <span class="op">&lt;-</span> <span class="st">"B"</span> <span class="co"># add column name with the name of the country</span>

<span class="co"># Join data of country A and country B in one object</span>
<span class="va">all_countries</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">countryA_demo_data</span>, <span class="va">countryB_demo_data</span><span class="op">)</span>

<span class="co"># Reference population</span>
<span class="va">standard_pop_data</span> <span class="op">&lt;-</span> <span class="fu">rio</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/rio/man/import.html">import</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"world_standard_population_by_sex.csv"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<!-- ======================================================= -->
</div>
<div id="one-row-per-stratum" class="section level3" number="17.2.3">
<h3>
<span class="header-section-number">17.2.3</span> One row per stratum<a class="anchor" aria-label="anchor" href="#one-row-per-stratum"><i class="fas fa-link"></i></a>
</h3>
<p>We need datasets with one row per stratum, while the current <code>all_countries</code> object has males and females listed on the same row.</p>
<div class="sourceCode" id="cb732"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Make a data frame for males only and change the column name m</span>
<span class="va">males_countries</span> <span class="op">&lt;-</span> <span class="va">all_countries</span> <span class="op">%&gt;%</span> <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">Country</span>, <span class="va">age_cat5</span>, <span class="va">m</span><span class="op">)</span> <span class="co"># make dataframe for males only</span>
<span class="va">males_countries</span> <span class="op">&lt;-</span> <span class="va">males_countries</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>Tot <span class="op">=</span> <span class="va">m</span><span class="op">)</span> <span class="co"># rename columns</span>
<span class="va">males_countries</span><span class="op">$</span><span class="va">Sex</span> <span class="op">&lt;-</span> <span class="st">"Male"</span> <span class="co"># add column containing male sex</span>

<span class="co"># Do the same for females</span>
<span class="va">females_countries</span> <span class="op">&lt;-</span> <span class="va">all_countries</span> <span class="op">%&gt;%</span> <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">Country</span>, <span class="va">age_cat5</span>, <span class="va">f</span><span class="op">)</span> 
<span class="va">females_countries</span> <span class="op">&lt;-</span> <span class="va">females_countries</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>Tot <span class="op">=</span> <span class="va">f</span><span class="op">)</span>
<span class="va">females_countries</span><span class="op">$</span><span class="va">Sex</span> <span class="op">&lt;-</span> <span class="st">"Female"</span> <span class="co"># add column containing female sex</span>

<span class="co"># Join the rows to finalize the population table with 1 row per stratum</span>
<span class="va">poptable_countries</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">males_countries</span>, <span class="va">females_countries</span><span class="op">)</span> 
<span class="va">poptable_countries</span> <span class="op">&lt;-</span> <span class="va">poptable_countries</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>AgeGroup <span class="op">=</span> <span class="va">age_cat5</span><span class="op">)</span> <span class="co"># rename column name so it matches the column name of the reference population dataset</span>

<span class="co"># Remove specific string from column values</span>
<span class="va">poptable_countries</span> <span class="op">&lt;-</span> <span class="va">poptable_countries</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>AgeGroup <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">gsub</a></span><span class="op">(</span><span class="st">"\\+"</span>, <span class="st">""</span>, <span class="va">AgeGroup</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<!-- ======================================================= -->
</div>
<div id="add-mortality-numbers" class="section level3" number="17.2.4">
<h3>
<span class="header-section-number">17.2.4</span> Add mortality numbers<a class="anchor" aria-label="anchor" href="#add-mortality-numbers"><i class="fas fa-link"></i></a>
</h3>
<p>We currently do not have number of deaths for each of the strata in our <code>poptable_countries</code> dataset, so we will need to add these. For the purpose of this analysis, we will add fictional data. Alternatively,</p>
<div class="sourceCode" id="cb733"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Make a vector with number of deaths</span>
<span class="va">mortality_n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">224</span>, <span class="fl">257</span>, <span class="fl">251</span>, <span class="fl">245</span>, <span class="fl">334</span>, <span class="fl">245</span>, <span class="fl">154</span>, <span class="fl">189</span>, <span class="fl">334</span>, <span class="fl">342</span>, <span class="fl">565</span>, <span class="fl">432</span>, <span class="fl">543</span>, <span class="fl">432</span>, <span class="fl">245</span>, <span class="fl">543</span>, <span class="fl">234</span>, <span class="fl">354</span>, <span class="co"># for males of country A</span>
                 <span class="fl">34</span>, <span class="fl">37</span>, <span class="fl">51</span>, <span class="fl">145</span>, <span class="fl">434</span>, <span class="fl">120</span>, <span class="fl">100</span>, <span class="fl">143</span>, <span class="fl">307</span>, <span class="fl">354</span>, <span class="fl">463</span>, <span class="fl">639</span>, <span class="fl">706</span>, <span class="fl">232</span>, <span class="fl">275</span>, <span class="fl">543</span>, <span class="fl">234</span>, <span class="fl">274</span>, <span class="co"># for males of country B</span>
                 <span class="fl">194</span>, <span class="fl">254</span>, <span class="fl">232</span>, <span class="fl">214</span>, <span class="fl">316</span>, <span class="fl">224</span>, <span class="fl">163</span>, <span class="fl">167</span>, <span class="fl">354</span>, <span class="fl">354</span>, <span class="fl">463</span>, <span class="fl">574</span>, <span class="fl">493</span>, <span class="fl">295</span>, <span class="fl">175</span>, <span class="fl">380</span>, <span class="fl">177</span>, <span class="fl">392</span>, <span class="co"># for females of country A</span>
                 <span class="fl">54</span>, <span class="fl">24</span>, <span class="fl">32</span>, <span class="fl">154</span>, <span class="fl">276</span>, <span class="fl">254</span>, <span class="fl">123</span>, <span class="fl">164</span>, <span class="fl">254</span>, <span class="fl">354</span>, <span class="fl">453</span>, <span class="fl">654</span>, <span class="fl">435</span>, <span class="fl">354</span>, <span class="fl">165</span>, <span class="fl">432</span>, <span class="fl">287</span>, <span class="fl">395</span><span class="op">)</span> <span class="co"># for females of country B</span>

<span class="co"># Make dataset including deaths</span>
<span class="va">poptable_countries</span><span class="op">$</span><span class="va">Deaths</span> <span class="op">&lt;-</span> <span class="va">mortality_n</span> <span class="co"># add column with number of deaths</span>

<span class="co"># Create factor levels </span>
<span class="va">poptable_countries</span> <span class="op">&lt;-</span> <span class="va">poptable_countries</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>AgeGroup <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">AgeGroup</span>, 
                                                                      levels<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"0-4"</span>, <span class="st">"5-9"</span>, <span class="st">"10-14"</span>,
                                                                                <span class="st">"15-19"</span>, <span class="st">"20-24"</span>, <span class="st">"25-29"</span>,
                                                                                <span class="st">"30-34"</span>, <span class="st">"35-39"</span>, <span class="st">"40-44"</span>,
                                                                                <span class="st">"45-49"</span>, <span class="st">"50-54"</span>, <span class="st">"55-59"</span>,
                                                                                <span class="st">"60-64"</span>, <span class="st">"65-69"</span>, <span class="st">"70-74"</span>,
                                                                                <span class="st">"75-79"</span>, <span class="st">"80-84"</span>, <span class="st">"85"</span><span class="op">)</span><span class="op">)</span>,
                                                    Sex <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Sex</span>, levels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Male"</span>, <span class="st">"Female"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
                                   
<span class="co"># Arrange by Country and AgeGroup</span>
<span class="va">poptable_countries</span> <span class="op">&lt;-</span> <span class="va">poptable_countries</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">Country</span>, <span class="va">AgeGroup</span>, <span class="va">Sex</span><span class="op">)</span></code></pre></div>
<p><span style="color: orange;"><strong><em>CAUTION:</em></strong> NB. If you have few deaths per stratum, use 10-, or 15-year categories, instead of 5-year categories for age, or combine categories</span></p>
<!-- ======================================================= -->
</div>
<div id="prepare-reference-population" class="section level3" number="17.2.5">
<h3>
<span class="header-section-number">17.2.5</span> Prepare reference population<a class="anchor" aria-label="anchor" href="#prepare-reference-population"><i class="fas fa-link"></i></a>
</h3>
<p>The values of the column <code>AgeGroup</code> from the <code>standard_pop_data</code> contain the word “years” and “plus”, while those of the <code>poptable_country</code> do not. We will have to remove this string to make it match.</p>
<div class="sourceCode" id="cb734"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Remove specific string from column values</span>
<span class="va">standard_pop</span> <span class="op">&lt;-</span> <span class="va">standard_pop_data</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>AgeGroup <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">gsub</a></span><span class="op">(</span><span class="st">"years"</span>, <span class="st">""</span>, <span class="va">AgeGroup</span><span class="op">)</span><span class="op">)</span>
<span class="va">standard_pop</span> <span class="op">&lt;-</span> <span class="va">standard_pop</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>AgeGroup <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">gsub</a></span><span class="op">(</span><span class="st">"plus"</span>, <span class="st">""</span>, <span class="va">AgeGroup</span><span class="op">)</span><span class="op">)</span>
<span class="va">standard_pop</span> <span class="op">&lt;-</span> <span class="va">standard_pop</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>AgeGroup <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">gsub</a></span><span class="op">(</span><span class="st">" "</span>, <span class="st">""</span>, <span class="va">AgeGroup</span><span class="op">)</span><span class="op">)</span>

<span class="co"># Rename last column with total population numbers, this variable must be named pop</span>
<span class="va">standard_pop</span> <span class="op">&lt;-</span> <span class="va">standard_pop</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>pop <span class="op">=</span> <span class="va">WorldStandardPopulation</span><span class="op">)</span>

<span class="co"># Create factor levels </span>
<span class="va">standard_pop</span> <span class="op">&lt;-</span> <span class="va">standard_pop</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>AgeGroup <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">AgeGroup</span>, 
                                                          levels<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"0-4"</span>, <span class="st">"5-9"</span>, <span class="st">"10-14"</span>,
                                                                    <span class="st">"15-19"</span>, <span class="st">"20-24"</span>, <span class="st">"25-29"</span>,
                                                                    <span class="st">"30-34"</span>, <span class="st">"35-39"</span>, <span class="st">"40-44"</span>,
                                                                    <span class="st">"45-49"</span>, <span class="st">"50-54"</span>, <span class="st">"55-59"</span>,
                                                                    <span class="st">"60-64"</span>, <span class="st">"65-69"</span>, <span class="st">"70-74"</span>,
                                                                    <span class="st">"75-79"</span>, <span class="st">"80-84"</span>, <span class="st">"85"</span><span class="op">)</span><span class="op">)</span>,
                                        Sex <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Sex</span>, levels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Male"</span>, <span class="st">"Female"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
                                   
<span class="co"># Arrange by AgeGroup</span>
<span class="va">standard_pop</span> <span class="op">&lt;-</span> <span class="va">standard_pop</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">AgeGroup</span>, <span class="va">Sex</span>, <span class="va">pop</span><span class="op">)</span>

<span class="co"># Add standard_pop to poptables_countries object (we need this in one dataset for **PHEindicatormethods**)</span>
<span class="va">countries_alldata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">poptable_countries</span>, <span class="va">standard_pop</span>, by<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"AgeGroup"</span>, <span class="st">"Sex"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<!-- ======================================================= -->
</div>
</div>
<div id="dsr-package" class="section level2" number="17.3">
<h2>
<span class="header-section-number">17.3</span> <strong>dsr</strong> package<a class="anchor" aria-label="anchor" href="#dsr-package"><i class="fas fa-link"></i></a>
</h2>
<h2>
Calculating and comparing directly standardized rates using the <strong>dsr</strong> package
<a class="anchor" aria-label="anchor" href="#dsr-package"><i class="fas fa-link"></i></a>
</h2>
<p>Remember, we made 1) the <code>poptable_countries</code> object, which is a population table with the number of population and number of deaths per stratum per country 2) the <code>standard_pop</code> object, containing the number of population per stratum for our reference population, the World Standard Population.</p>
<p>The <strong>dsr</strong> package allows you to calculate and compare directly standardized rates (no indirectly standardized rates!).</p>
<!-- ======================================================= -->
<div id="standardized-rates" class="section level3" number="17.3.1">
<h3>
<span class="header-section-number">17.3.1</span> Standardized rates<a class="anchor" aria-label="anchor" href="#standardized-rates"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb735"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Calculate rates per country directly standardized for age and sex</span>
<span class="va">mortality_rate</span> <span class="op">&lt;-</span> <span class="fu">dsr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/dsr/man/dsr.html">dsr</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">poptable_countries</span>, <span class="co"># specify object containing number of deaths per stratum</span>
                      event<span class="op">=</span><span class="va">Deaths</span>, <span class="co"># column containing number of deaths per stratum </span>
                      fu<span class="op">=</span><span class="va">Tot</span>, <span class="co"># column containing number of population per stratum</span>
                      subgroup<span class="op">=</span><span class="va">Country</span>, <span class="co"># units we would like to compare</span>
                      <span class="va">AgeGroup</span>, <span class="va">Sex</span>, <span class="co"># characteristics to which we would like to standardize </span>
                      refdata<span class="op">=</span><span class="va">standard_pop</span>, <span class="co"># reference population, with numbers in column called pop</span>
                      method<span class="op">=</span><span class="st">"gamma"</span>, <span class="co"># method to calculate 95% CI</span>
                      sig<span class="op">=</span><span class="fl">0.95</span>, <span class="co"># significance level</span>
                      mp<span class="op">=</span><span class="fl">100000</span>, <span class="co"># we want rates per 100.000 population</span>
                      decimals<span class="op">=</span><span class="fl">2</span><span class="op">)</span> <span class="co"># number of decimals)</span></code></pre></div>
<pre><code>## Joining, by = c("AgeGroup", "Sex")</code></pre>
<div class="sourceCode" id="cb737"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Print table</span>
<span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">mortality_rate</span><span class="op">)</span> <span class="co"># show mortality rate before and after direct standardization</span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="6%">
<col width="7%">
<col width="8%">
<col width="17%">
<col width="11%">
<col width="11%">
<col width="15%">
<col width="10%">
<col width="10%">
</colgroup>
<thead><tr class="header">
<th align="left">Subgroup</th>
<th align="right">Numerator</th>
<th align="right">Denominator</th>
<th align="right">Crude Rate (per 1e+05)</th>
<th align="right">95% LCL (Crude)</th>
<th align="right">95% UCL (Crude)</th>
<th align="right">Std Rate (per 1e+05)</th>
<th align="right">95% LCL (Std)</th>
<th align="right">95% UCL (Std)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">A</td>
<td align="right">11344</td>
<td align="right">86790567</td>
<td align="right">13.07</td>
<td align="right">12.83</td>
<td align="right">13.31</td>
<td align="right">23.57</td>
<td align="right">23.08</td>
<td align="right">24.06</td>
</tr>
<tr class="even">
<td align="left">B</td>
<td align="right">9955</td>
<td align="right">52898281</td>
<td align="right">18.82</td>
<td align="right">18.45</td>
<td align="right">19.19</td>
<td align="right">19.33</td>
<td align="right">18.46</td>
<td align="right">20.22</td>
</tr>
</tbody>
</table></div>
<p>Here, we see that while country A had a lower crude mortality rate than country B, it has a higher standardized rate after direct age and sex standardization.</p>
<!-- ======================================================= -->
</div>
<div id="standardized-rate-ratios" class="section level3" number="17.3.2">
<h3>
<span class="header-section-number">17.3.2</span> Standardized rate ratios<a class="anchor" aria-label="anchor" href="#standardized-rate-ratios"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb738"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Calculate RR</span>
<span class="va">mortality_rr</span> <span class="op">&lt;-</span> <span class="fu">dsr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/dsr/man/dsrr.html">dsrr</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">poptable_countries</span>, <span class="co"># specify object containing number of deaths per stratum</span>
                    event<span class="op">=</span><span class="va">Deaths</span>, <span class="co"># column containing number of deaths per stratum </span>
                    fu<span class="op">=</span><span class="va">Tot</span>, <span class="co"># column containing number of population per stratum</span>
                    subgroup<span class="op">=</span><span class="va">Country</span>, <span class="co"># units we would like to compare</span>
                    <span class="va">AgeGroup</span>, <span class="va">Sex</span>, <span class="co"># characteristics to which we would like to standardize </span>
                    refdata<span class="op">=</span><span class="va">standard_pop</span>, <span class="co"># reference population, with numbers in column called pop</span>
                    refgroup<span class="op">=</span><span class="st">"B"</span>, <span class="co"># reference for comparison</span>
                    estimate<span class="op">=</span><span class="st">"ratio"</span>, <span class="co"># type of estimate</span>
                    sig<span class="op">=</span><span class="fl">0.95</span>, <span class="co"># significance level</span>
                    mp<span class="op">=</span><span class="fl">100000</span>, <span class="co"># we want rates per 100.000 population</span>
                    decimals<span class="op">=</span><span class="fl">2</span><span class="op">)</span> <span class="co"># number of decimals)</span></code></pre></div>
<pre><code>## Joining, by = c("AgeGroup", "Sex")</code></pre>
<div class="sourceCode" id="cb740"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Print table</span>
<span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">mortality_rr</span><span class="op">)</span> </code></pre></div>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="13%">
<col width="11%">
<col width="25%">
<col width="19%">
<col width="15%">
<col width="15%">
</colgroup>
<thead><tr class="header">
<th align="left">Comparator</th>
<th align="left">Reference</th>
<th align="right">Std Rate (per 1e+05)</th>
<th align="right">Rate Ratio (RR)</th>
<th align="right">95% LCL (RR)</th>
<th align="right">95% UCL (RR)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">A</td>
<td align="left">B</td>
<td align="right">23.57</td>
<td align="right">1.22</td>
<td align="right">1.17</td>
<td align="right">1.27</td>
</tr>
<tr class="even">
<td align="left">B</td>
<td align="left">B</td>
<td align="right">19.33</td>
<td align="right">1.00</td>
<td align="right">0.94</td>
<td align="right">1.06</td>
</tr>
</tbody>
</table></div>
<p>The standardized mortality rate is 1.22 times higher in country A compared to country B (95% CI 1.17-1.27).</p>
<!-- ======================================================= -->
</div>
<div id="standardized-rate-difference" class="section level3" number="17.3.3">
<h3>
<span class="header-section-number">17.3.3</span> Standardized rate difference<a class="anchor" aria-label="anchor" href="#standardized-rate-difference"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb741"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Calculate RD</span>
<span class="va">mortality_rd</span> <span class="op">&lt;-</span> <span class="fu">dsr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/dsr/man/dsrr.html">dsrr</a></span><span class="op">(</span>data<span class="op">=</span><span class="va">poptable_countries</span>, <span class="co"># specify object containing number of deaths per stratum</span>
                    event<span class="op">=</span><span class="va">Deaths</span>, <span class="co"># column containing number of deaths per stratum </span>
                    fu<span class="op">=</span><span class="va">Tot</span>, <span class="co"># column containing number of population per stratum</span>
                    subgroup<span class="op">=</span><span class="va">Country</span>, <span class="co"># units we would like to compare</span>
                    <span class="va">AgeGroup</span>, <span class="va">Sex</span>, <span class="co"># characteristics to which we would like to standardize </span>
                    refdata<span class="op">=</span><span class="va">standard_pop</span>, <span class="co"># reference population, with numbers in column called pop</span>
                    refgroup<span class="op">=</span><span class="st">"B"</span>, <span class="co"># reference for comparison</span>
                    estimate<span class="op">=</span><span class="st">"difference"</span>, <span class="co"># type of estimate</span>
                    sig<span class="op">=</span><span class="fl">0.95</span>, <span class="co"># significance level</span>
                    mp<span class="op">=</span><span class="fl">100000</span>, <span class="co"># we want rates per 100.000 population</span>
                    decimals<span class="op">=</span><span class="fl">2</span><span class="op">)</span> <span class="co"># number of decimals)</span></code></pre></div>
<pre><code>## Joining, by = c("AgeGroup", "Sex")</code></pre>
<div class="sourceCode" id="cb743"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Print table</span>
<span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">mortality_rd</span><span class="op">)</span> </code></pre></div>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="12%">
<col width="11%">
<col width="23%">
<col width="23%">
<col width="14%">
<col width="14%">
</colgroup>
<thead><tr class="header">
<th align="left">Comparator</th>
<th align="left">Reference</th>
<th align="right">Std Rate (per 1e+05)</th>
<th align="right">Rate Difference (RD)</th>
<th align="right">95% LCL (RD)</th>
<th align="right">95% UCL (RD)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">A</td>
<td align="left">B</td>
<td align="right">23.57</td>
<td align="right">4.24</td>
<td align="right">3.24</td>
<td align="right">5.24</td>
</tr>
<tr class="even">
<td align="left">B</td>
<td align="left">B</td>
<td align="right">19.33</td>
<td align="right">0.00</td>
<td align="right">-1.24</td>
<td align="right">1.24</td>
</tr>
</tbody>
</table></div>
<p>Country A has 4.24 additional deaths per 100.000 population (95% CI 3.24-5.24) compared to country A.</p>
<!-- ======================================================= -->
</div>
</div>
<div id="pheindicatormethods-package" class="section level2" number="17.4">
<h2>
<span class="header-section-number">17.4</span> <strong>PHEindicatormethods</strong> package<a class="anchor" aria-label="anchor" href="#pheindicatormethods-package"><i class="fas fa-link"></i></a>
</h2>
<p>Another way of calculating standardized rates is with the <strong>PHEindicatormethods</strong> package. This package allows you to calculate directly as well as indirectly standardized rates. We need the reference (standard) population as well as the country-specific mortality and population data in one object, which we have made earlier: <code>countries_alldata</code>.</p>
<!-- ======================================================= -->
<div id="directly-standardized-rates" class="section level3" number="17.4.1">
<h3>
<span class="header-section-number">17.4.1</span> Directly standardized rates<a class="anchor" aria-label="anchor" href="#directly-standardized-rates"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb744"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Calculate rates per country directly standardized for age and sex</span>
<span class="va">mortality_rate_phe</span> <span class="op">&lt;-</span> <span class="va">countries_alldata</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">Country</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">PHEindicatormethods</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/PHEindicatormethods/man/phe_dsr.html">phe_dsr</a></span><span class="op">(</span><span class="va">Deaths</span>, <span class="co"># observed number of events (column name)</span>
                               n <span class="op">=</span> <span class="va">Tot</span>, <span class="co"># non-standard pops for category i.e. ageband</span>
                               stdpop <span class="op">=</span> <span class="va">pop</span>, <span class="co"># standard populations for each stratum</span>
                               stdpoptype <span class="op">=</span> <span class="st">"field"</span><span class="op">)</span> <span class="co"># standalone vector or field name, for the std populations</span>
                                                   
<span class="co"># Print table</span>
<span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">mortality_rate_phe</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="6%">
<col width="10%">
<col width="8%">
<col width="15%">
<col width="15%">
<col width="15%">
<col width="9%">
<col width="12%">
<col width="5%">
</colgroup>
<thead><tr class="header">
<th align="left">Country</th>
<th align="right">total_count</th>
<th align="right">total_pop</th>
<th align="right">value</th>
<th align="right">lowercl</th>
<th align="right">uppercl</th>
<th align="left">confidence</th>
<th align="left">statistic</th>
<th align="left">method</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">A</td>
<td align="right">11344</td>
<td align="right">86790567</td>
<td align="right">23.56685849327109</td>
<td align="right">23.08106689236966</td>
<td align="right">24.05943770431395</td>
<td align="left">95%</td>
<td align="left">dsr per 100000</td>
<td align="left">Dobson</td>
</tr>
<tr class="even">
<td align="left">B</td>
<td align="right">9955</td>
<td align="right">52898281</td>
<td align="right">19.32549423719546</td>
<td align="right">18.45515902513744</td>
<td align="right">20.20881745377039</td>
<td align="left">95%</td>
<td align="left">dsr per 100000</td>
<td align="left">Dobson</td>
</tr>
</tbody>
</table></div>
<!-- ======================================================= -->
</div>
</div>
<div id="resources-10" class="section level2" number="17.5">
<h2>
<span class="header-section-number">17.5</span> Resources<a class="anchor" aria-label="anchor" href="#resources-10"><i class="fas fa-link"></i></a>
</h2>
<p><span style="color: darkgreen;"><strong><em>TIP:</em></strong> If you would like to see another reproducible example than listed in this Handbook, please go to <a href="https://mran.microsoft.com/snapshot/2020-02-12/web/packages/dsr/vignettes/dsr.html" class="uri">https://mran.microsoft.com/snapshot/2020-02-12/web/packages/dsr/vignettes/dsr.html</a>.</span></p>
<p><strong>PHEindicatormethods</strong> reference file: <a href="https://cran.r-project.org/web/packages/PHEindicatormethods/PHEindicatormethods.pdf" class="uri">https://cran.r-project.org/web/packages/PHEindicatormethods/PHEindicatormethods.pdf</a></p>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="simple-statistical-tests.html"><span class="header-section-number">16</span> Simple statistical tests</a></div>
<div class="next"><a href="moving-averages.html"><span class="header-section-number">18</span> Moving averages</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#standardization"><span class="header-section-number">17</span> Standardization</a></li>
<li><a class="nav-link" href="#overview-10"><span class="header-section-number">17.1</span> Overview</a></li>
<li><a class="nav-link" href="#preparation-8"><span class="header-section-number">17.2</span> Preparation</a></li>
<li>
<a class="nav-link" href="#preparation-8">
Preparation
</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#load-packages-1"><span class="header-section-number">17.2.1</span> Load packages</a></li>
<li><a class="nav-link" href="#load-data-2"><span class="header-section-number">17.2.2</span> Load data</a></li>
<li><a class="nav-link" href="#one-row-per-stratum"><span class="header-section-number">17.2.3</span> One row per stratum</a></li>
<li><a class="nav-link" href="#add-mortality-numbers"><span class="header-section-number">17.2.4</span> Add mortality numbers</a></li>
<li><a class="nav-link" href="#prepare-reference-population"><span class="header-section-number">17.2.5</span> Prepare reference population</a></li>
</ul>
</li>
<li><a class="nav-link" href="#dsr-package"><span class="header-section-number">17.3</span> dsr package</a></li>
<li>
<a class="nav-link" href="#dsr-package">
Calculating and comparing directly standardized rates using the dsr package
</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#standardized-rates"><span class="header-section-number">17.3.1</span> Standardized rates</a></li>
<li><a class="nav-link" href="#standardized-rate-ratios"><span class="header-section-number">17.3.2</span> Standardized rate ratios</a></li>
<li><a class="nav-link" href="#standardized-rate-difference"><span class="header-section-number">17.3.3</span> Standardized rate difference</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#pheindicatormethods-package"><span class="header-section-number">17.4</span> PHEindicatormethods package</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#directly-standardized-rates"><span class="header-section-number">17.4.1</span> Directly standardized rates</a></li></ul>
</li>
<li><a class="nav-link" href="#resources-10"><span class="header-section-number">17.5</span> Resources</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>R Handbook for Epidemiologists</strong>" was written by the handbook team. It was last built on 2021-02-22.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>
</body>
</html>
