
# if/else & 'for' loops {.tabset .tabset-fade}  


<!-- ======================================================= -->
## Overview {.tabset .tabset-fade .tabset-pills}




<!-- ======================================================= -->
## Preparation {.tabset .tabset-fade .tabset-pills}

Keep the title of this section as "Preparation".  
Data preparation steps such as:  

* Loading dataset  
* Adding or changing variables  
* melting, pivoting, grouping, etc.   


<!-- ======================================================= -->
## if-else {.tabset .tabset-fade .tabset-pills}

This tab can be renamed. 
This tab should demonstrate execution of the task using recommended package/approach. For example, using a package customized for this task where the execution is simple and fast but perhaps less customizable. For example using *incidence* package to create an epicurve.




<!-- ======================================================= -->
## 'for' loops {.tabset .tabset-fade .tabset-pills}

This tab can be re-named. 
This tab should demonstrate execution of the task a more standard/core package (e.g. ggplot2, or base R) that allows for more flexibility in the output or more package stability. For example, showing how to create an epicurve using *ggplot2*. 


<!-- ======================================================= -->
### Tracking progress {.tabset .tabset-fade .tabset-pills}

```
for (row_origin in 1:nrow(ct_metrics)){
  # print progress
  if(row_origin %% 100==0){
    print(row_origin)
  }
  
```


<!-- ======================================================= -->
## Resources {.tabset .tabset-fade .tabset-pills}





