
# Tables {.tabset .tabset-fade}  

The Page title should be succinct. Consider adding a tag with no spaces into the curly brackets, such as below. This can be used for internal links within the handbook. 
`{#title_tag .tabset .tabset-fade}`

<!-- ======================================================= -->
## Overview {.tabset .tabset-fade .tabset-pills}

Keep the title of this section as "Overview".  
This tab should include:  

* Textual overview of the purpose of this page  
* Small image showing outputs   



<!-- ======================================================= -->
## Preparation {.tabset .tabset-fade .tabset-pills}

Keep the title of this section as "Preparation".  
Data preparation steps such as:  

* Loading dataset  
* Adding or changing variables  
* melting, pivoting, grouping, etc.   


<!-- ======================================================= -->
## Manually {.tabset .tabset-fade .tabset-pills}



<!-- ======================================================= -->
## From data frame {.tabset .tabset-fade .tabset-pills}

knitr::kable
DT



<!-- ======================================================= -->
## Summarizing dataframe {.tabset .tabset-fade .tabset-pills}


<!-- ======================================================= -->
## From modelresults {.tabset .tabset-fade .tabset-pills}

For publication

<!-- ======================================================= -->
## Other {.tabset .tabset-fade .tabset-pills}
quickly changing the denominator (per 100,000, etc.)



<!-- ======================================================= -->
## Resources {.tabset .tabset-fade .tabset-pills}

This tab should stay with the name "Resources".
Links to other online tutorials or resources.




